name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build
      run: msbuild /p:Configuration=Release TeamBuilderPkmn.sln

    - name: Upload release
      uses: yakuhzi/action-release@v1
      with:
        file: \TeamBuilderPkmn\bin\Release\TeamBuilderPkmn.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
